### ISSUE TITLE
Environment Setup: Docker, IDE, etc

### ISSUE THREAD

**Issue by nmsohn** [WellyKorgis/project-blind-api#1]
## User Story
- As a developer/devops, I want to have a unified environment across the team so that there is no need for the individual to set up their own environment every time

## Definition of Done (Acceptance Criteria)
- Install the following:
  - Git
  - VS Code, IntelliJ (as preferred)
  - Java SDK
  - Docker desktop
  - NodeJS
- Clone both project-blind-web, project-blind-api repos

**Comment by seegya** [comment]
다 있으니 닫겠습니당
