### ISSUE TITLE
DB: Create a Job Category table using ORM

### ISSUE THREAD

**Issue by nmsohn** [WellyKorgis/project-blind-api#16]
# User Story
As a developer, I want to create SQL scripts for user so that I can create a Job Category table and store data there

# Acceptance Criteria
- In a docker container, there is a Job Category table in the database (blind-db)

**Comment by seegya** [comment]
도커 호스트에서 postgresql 컨테이너 실행 해 봤을 때 유저만 보여요! 혹시 확인 한 번 만 더 해 주실 수 있으신가요?
