### ISSUE TITLE
Environment Setup:  Create a docker script to set up the environment

### ISSUE THREAD

**Issue by nmsohn** [WellyKorgis/project-blind-api#4]
## User Story
- As a developer/devops, I want to have a unified environment across the team so that there is no need for the individual to set up their own environment every time

## Definition of Done (Acceptance Criteria)
- Dockerfile

**Comment by seegya** [comment]
아 미쳐 web에다가 만들어놨어요. api에 넣어놨으니 리뷰부탁합니당
