### ISSUE TITLE
Github Setup: Branch policy, PR templates, PR/CL practices, Guidelines for consistent convention

### ISSUE THREAD

**Issue by nmsohn** [WellyKorgis/project-blind-api#5]
## User Story
- As a developer/devops, I want to create guidelines for branch strategy, PR/CL practices so that there is consistency in the convention across the team

## Definition of Done (Acceptance Criteria)
- Define branch strategy
- Define PR/CL practices
- Draft development guidelines
- Add Slack integration

**Comment by SG-20** [comment]
d
