### ISSUE TITLE
SPIKE: Investigate Sonarcube workflow using Github Action

### ISSUE THREAD

**Issue by nmsohn** [WellyKorgis/project-blind-api#70]

**Comment by seegya** [comment]
![Image](https://user-images.githubusercontent.com/77556070/174430127-87ec21af-1c5d-42bc-9a2f-ac2fff1201b2.png)



![Image](https://user-images.githubusercontent.com/77556070/174430145-01661dff-c7d8-4366-a335-5daf66ae1129.png)

시크릿이 세팅에 안보이네용 언니는 세팅 클릭하면 보이시나요??

**Comment by nmsohn** [comment]
방금 권한 드렸으니 다시 시도해보세요

**Comment by seegya** [comment]
`https://jojoldu.tistory.com/662`

이거 참고해서 했습니당
